apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-sidecar
  annotations:
    policies.kyverno.io/title: Inject Sidecar Container
spec:
  rules:
    - name: inject-sidecar
      match:
        any:
          - resources:
              kinds:
                - Deployment
      mutate:
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  (vpc-lattices-svcs.amazonaws.com/agent-inject): "true"
              spec:
                initContainers: # IPTables rules are updated in init container
                  - image: public.ecr.aws/d2c6w7a3/iptables
                    name: iptables-init
                    securityContext:
                      capabilities:
                        add:
                          - NET_ADMIN
                    command: # Adding --uid-owner 101 here to prevent traffic from envoy proxy itself from being redirected, which prevents an infinite loop
                      - /bin/sh
                      - -c
                      - >
                        iptables -t nat -N EGRESS_PROXY;
                        iptables -t nat -A OUTPUT -p tcp -d 169.254.171.0/24 -j EGRESS_PROXY;
                        iptables -t nat -A EGRESS_PROXY -m owner --uid-owner 101 -j RETURN;
                        iptables -t nat -A EGRESS_PROXY -p tcp -j REDIRECT --to-ports 8080;
                containers:
                  - name: sigv4proxy
                    env:
                      - name: AWS_REGION
                        value: "{{ .Values.region }}"
                    image: public.ecr.aws/seb-demo/aws-sigv4-proxy:latest
                    args: ["--unsigned-payload", "--log-failed-requests", "-v", "--log-signing-process", "--name", "vpc-lattice-svcs", "--region", "{{ .Values.region }}", "--upstream-url-scheme", "http"]
                    ports:
                      - containerPort: 8080
                        name: proxy
                        protocol: TCP
                    securityContext:
                      runAsUser: 101
