apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  filters.conf: |
    [FILTER]
      Name parser
      Match fargate-logs-flblogs.*
      Key_Name log
      Parser fluentbit
      Preserve_Key True
      Reserve_Data True
    [FILTER]
      Name parser
      Match fargate-logs-kube.*
      Key_Name log
      Parser crio
      Preserve_Key True
      Reserve_Data True
  flb_log_cw: "true"
  output.conf: |
    [OUTPUT]
      Name cloudwatch_logs
      Match *
      region us-west-2
      log_group_name /fargate-serverless/fargate-fluentbit-logs2024091817475518540000000a
      log_stream_prefix fargate-logs-
      auto_create_group true
  parsers.conf: |
    [PARSER]
      Name crio
      Format regex
      Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>P|F) (?<log>.*)$
      Time_Key    time
      Time_Format %Y/%m/%d %H:%M:%S
      Time_Keep On
      Decode_Field_As json message
    [PARSER]
      Name fluentbit
      Format regex
      Regex ^(?<time>[^ ]+) (?<log_level>[^ ]+) (?<message>.+)$
      Time_Key time
      Time_Format %Y/%m/%d
      Time_Keep On
      Decode_Field_As json message
immutable: false
