kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
  labels:
data:
  flb_log_cw: "true"  # Ships Fluent Bit process logs to CloudWatch.
  output.conf: |
    [OUTPUT]
        Name cloudwatch
        Match *
        region us-west-2
        log_group_name /fargate-serverless/fargate-fluentbit-logs2024091817475518540000000a
        log_stream_prefix from-fluent-bit-
        auto_create_group true
