apiVersion: v1
immutable: false
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-18T17:47:57Z"
  name: aws-logging
  namespace: aws-observability
data:
  filters.conf: |
    # Default Filters
    [FILTER]
        Name parser
        Match fargate-logs-kube.var.log.containers.*
        Key_Name log
        Parser default
        Preserve_Key True
        Reserve_Data True
    # Fluentbit Filters
    [FILTER]
        Name parser
        Match fargate-logs-flblogs.var.log.fluent-bit.log
        Key_Name log
        Parser fluentbit
        Preserve_Key True
        Reserve_Data True
  flb_log_cw: "true"
  output.conf: |
    # Default output
    [OUTPUT]
        Name cloudwatch_logs
        Match fargate-logs-kube.var.log.containers.*
        region us-west-2
        log_group_name /fargate-serverless/qualquermerda-logs
        log_stream_prefix qualquermerda-logs-
        auto_create_group true
    # Fluentbit outputs
    [OUTPUT]
        Name cloudwatch_logs
        Match fargate-logs-flblogs.var.log.fluent-bit.log
        region us-west-2
        log_group_name /fargate-serverless/fluentbit-logs
        log_stream_prefix fluentbit-logs-
        auto_create_group true

  parsers.conf: |
    # Default log Parser
    [PARSER]
        Name default
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>[^ ]+) (?<logtag>[^ ]+) (?<message>.+)$
        Time_Key time
        Time_Format %Y/%m/%d %H:%M:%S
        Time_Keep On
        Decode_Field_As json message
    # Fluentbit logs Parser
    [PARSER]
        Name fluentbit
        Format regex
        Regex ^(?<time>[^ ]+) (?<log_level>[^ ]+) (?<message>.+)$
        Time_Key time
        Time_Format %Y/%m/%d %H:%M:%S
        Time_Keep On
        Decode_Field_As json message
