apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: example
      image: nvcr.io/nvidia/pytorch:24.07-py3
      command: ['python3']
      args:
        [
          '-c',
          'import torch; print(torch.cuda.is_available()); print(torch.cuda.device_count())',
        ]
